version: '3.4'

services:
  site:
    image: dotnetcore
    ports:
      - target: 80
        published: 8888
    networks:
      - my_net
  api:
    image: dotnetcore-api
    networks:
      - my_net

networks:
  my_net:
    driver: overlay